name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types:
      - published

env:
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  NUGET_FEED: https://api.nuget.org/v3/index.json

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: restore format
      run: dotnet tool restore --configfile NuGet.config
    - name: check format
      run: dotnet format --check ./Motor.NET.sln

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore Motor.NET.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore Motor.NET.sln
    # - name: Test
    #   run: dotnet test --no-restore Motor.NET.sln
    # - name: Pack
    #   run: dotnet pack -v minimal -c Release --no-restore -o ./artifacts Motor.NET.sln
    - name: Publish Bridge
      run: dotnet publish -v minimal -c Release --no-restore -o ./artifacts-bridge ./src/Motor.Extensions.Hosting.Bridge/Motor.Extensions.Hosting.Bridge.csproj
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: artifacts
    #     path: ./artifacts/*.nupkg
    - name: Upload Artifact Bridge
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-bridge
        path: ./artifacts-bridge/*

  # deploy:
  #   needs: build
  #   if: github.event_name == 'release'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: artifacts
  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: 5.0.x
  #     - name: Push to NuGet Feed
  #       run: dotnet nuget push './artifacts/*.nupkg' --skip-duplicate --source $NUGET_FEED --api-key $NUGET_KEY

  build-bridge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: artifacts-bridge
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: github.event_name == 'release'
          context: ./artifacts-bridge
          tags: docker.pkg.github.com/gdatasoftwareag/motornet/bridge:latest,docker.pkg.github.com/gdatasoftwareag/motornet/bridge:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
