name: .NET Core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types:
      - published

env:
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  NUGET_FEED: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore Motor.NET.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore Motor.NET.sln
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal Motor.NET.sln
    - name: Pack
      run: dotnet pack -v minimal -c Release --no-restore -o ./artifacts Motor.NET.sln
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./artifacts/*.nupkg

  deploy:
    needs: build
    #if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: artifacts
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Push to NuGet Feed
        run: dotnet nuget push './artifacts/*.nupkg' --skip-duplicate --source $NUGET_FEED --api-key $NUGET_KEY