name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  merge_group:
    types: [checks_requested]
  release:
    types:
      - published

env:
  NUGET_API_KEY: ${{ secrets.NUGET_KEY }}
  NUGET_FEED: https://api.nuget.org/v3/index.json

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
      - name: check format
        run: |
          dotnet tool restore
          ./build.sh --target CheckFormat

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Build
        run: ./build.sh --target Artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: |
            ./artifacts/*.nupkg
            ./artifacts/*.snupkg
      - name: Upload Artifact Bridge
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-bridge
          path: ./artifacts-bridge/*

  test-net8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Test .NET8
        run: ./build.sh -t Test --dotnet-versions net8.0

  test-net9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
      - name: Test .NET9
        run: ./build.sh -t Test --dotnet-versions net9.0

          
  #code-ql:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Initialize CodeQL
  #    uses: github/codeql-action/init@v1
  #    with:
  #      languages: csharp
  #  - name: Setup .NET
  #    uses: actions/setup-dotnet@v1
  #    with:
  #      dotnet-version: 7.0.x
  #  - name: Install dependencies
  #    run: dotnet restore Motor.NET.slnx
  #  - name: Build
  #    run: dotnet build --configuration Release --no-restore Motor.NET.slnx
  #  - name: Perform CodeQL Analysis
  #    uses: github/codeql-action/analyze@v1

  deploy:
    needs: [build, format, test-net8, test-net9]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v8
        with:
          name: artifacts
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Push to NuGet feed
        run: ./build.sh -t NugetPush --artifacts-directory "${{ steps.download.outputs.download-path }}"

  build-bridge:
    needs: [build, format, test-net8, test-net9]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v8
        with:
          name: artifacts-bridge
      - name: Login to Github Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        run: /build.sh -t BridgeContainerImage --bridge-artifacts-directory "${{ steps.download.outputs.download-path }}"
