name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  merge_group:
    types: [checks_requested]
  release:
    types:
      - published

env:
  NUGET_API_KEY: ${{ secrets.NUGET_KEY }}
  NUGET_FEED: https://api.nuget.org/v3/index.json

jobs:
  cake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Login to GitHub Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Build
        run: |
          # this should not be necessary, but for some reason cake is not restoring tools correctly
          dotnet tool restore
          bash build.sh

          
  #code-ql:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Initialize CodeQL
  #    uses: github/codeql-action/init@v1
  #    with:
  #      languages: csharp
  #  - name: Setup .NET
  #    uses: actions/setup-dotnet@v1
  #    with:
  #      dotnet-version: 7.0.x
  #  - name: Install dependencies
  #    run: dotnet restore Motor.NET.slnx
  #  - name: Build
  #    run: dotnet build --configuration Release --no-restore Motor.NET.slnx
  #  - name: Perform CodeQL Analysis
  #    uses: github/codeql-action/analyze@v1
